# see /usr/share/doc/picom/examples/picom.sample.conf
shadow = true;
shadow-radius = 12;
shadow-opacity = .9
shadow-offset-x = -7;
shadow-offset-y = -7;
corner-radius = 8;
backend = "glx";
vsync = true;
use-damage = true;
